Update show_error.yml

diff --git a/.github/workflows/show_error.yml b/.github/workflows/show_error.yml
--- a/.github/workflows/show_error.yml
+++ b/.github/workflows/show_error.yml
@@ -10,5 +10,9 @@ jobs:
       - uses: actions/checkout@v3
       - name: Run a one-line script
         run: |
-          echo "::error file=app.js,line=1,col=5,endColumn=7::Error while running the script"
-          exit 1
+          GIT_BRANCH="${{ github.ref_name }}"
+          if [[ ! echo "$GIT_BRANCH" | grep -qE "^[a-zA-Z][-a-zA-Z0-9]*$" ]]; then
+            MSG="Invalid branch name \"$GIT_BRANCH\", branch name must match regex \"[a-zA-Z][-a-zA-Z0-9]*\""
+            echo "::error file=show_error.yml,line=14::$MSG"
+            exit 1
+          fi
